### ISSUE TITLE
Why was Germany removed in auth

### ISSUE THREAD

**Issue by mybayern1974** [Azure/terraform-provider-azurerm-restapi#29]
@magodo https://github.com/Azure/terraform-provider-azurerm-restapi/pull/24/files?authenticity_token=k%2F7uuFTGNittA%2FHO8cLoM%2FweHbH5DZyGwlYAN7vWi%2Fses9Ga7x3SLZjDa%2Fdr5XW9Xy4j3bVRA004nkzz6usJXg%3D%3D&file-filters%5B%5D=.go&hide-deleted-files=true#diff-5356bf0f66afc352baa83048e806849ba12ccf7cb478ad335478ae9718160cc6L27

**Comment by magodo** [comment]
@mybayern1974 See https://github.com/hashicorp/go-azure-helpers/pull/83.

**Comment by mybayern1974** [comment]
Yes that is the source of true in technique, but why doing that (remove Germany) per business perspective? 🤔 Though answering for that should be out of this project

**Comment by magodo** [comment]
@mybayern1974 Azure is offically closing the MS Cloud Germany: https://docs.microsoft.com/en-us/azure/germany/germany-welcome
